# Summer Curriculum - Week 1
## Tensors

This lesson is from the https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html website

I have not worked with tensors, pytorch, tensorflow or anything to do with any of these items. This is my first lesson that has to do with this subject. I am learning via that doc.pytorch.org website, specifically working within the 'Tesnors' lesson as of right now

Being that this is my first real lesson of my Summer curriculum, I am messing around with different ways to take notes on the lessons that I am completing within the notebook that I am working on, instead of just following the material mindlessly. I will be recording the lesson information as well as my thoughts on what the code is going to output within markdown blocks as well as in comments inside of the actual code blocks as well.

In [2]:
# Import the necessary libraries
import torch
import numpy as np

Tensors can be intitialized in several ways. One of which being directly from data, where the data type is automatically inferred.

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

Another way is from a numpy array

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

They can also be made from other tensors

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3310, 0.6321],
        [0.5575, 0.8320]]) 



Shape can be used to determine the dimesionality of an output tensor. Shape, itself is a tuple comprised of tensor dimensions.

In [11]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8390, 0.1492, 0.3999],
        [0.7484, 0.1815, 0.4165]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



Tensors have attributes like other entities do. Specifically, these attributes are their 1) Shape 2) Data Type and 3) The device on which they are stored.

In [12]:
# This obviously creates a tensor of shape (3, 4)
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}") # This should output a tuple of the tensor shape
print(f"Datatype of tensor: {tensor.dtype}") # I do not know what the default datatype for a tensor is, but I am going to assume int
print(f"Device tensor is stored on: {tensor.device}") # I really don't know what device it would be stored on, so I do not even know how to venture a guess

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


I was curious of whether the attributes that a tensor has are defaulted to any sepcfic value. We can determine the shape of a tensor when we generate one ourselves, but we can also see the shape of one if it is written organically instead of using a tensor function.

Additionally, I guessed that the default for the dtype was an int when it is really a float. This makes sense, and will continue to make more sense as we dig in further, becuase when we talk about neural networks and weights, discrete numbers are hardly ever used; things are more continuous so a float data type would be more appropriate.

We also talked about how the default device is the cpu vs a gpu. There is the option of switching between the two, but that is an expensive and time-intensive process that should not be done back and forth if it can be helped. It is important to know which device is the most appropriate for the undertaking and to set the tensor location to that as early as posisble. Additionally, tensors need to be in the same location if there are operatiosn that are going to be conducted using multiple different ones. The bottom line on the cpu v gpu conversation is that gpu is more useful for larger scale tensor operations while you can get by with using cpu as your device location for smaller tasks.

In [13]:
# Moving our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [16]:
# Conducting some operations on our tensor
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}") # Just prints the first row of the tensor
print(f"First column: {tensor[:, 0]}") # Prints the first column of the tensor
print(f"Last column: {tensor[..., -1]}") # Prints the last column of the tensor; ... captures all row entries for the column
tensor[:, 1] = 0 # Sets the value of the second column of the tensor to 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Tensors can also be join with each other

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1) # I think that this will concatenate to add more columns to the right of the original tensor


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


^ concatenating along dim = 1 just means adding the new tensor to the right of the old one. I believe that this would only work for tensors of the same shape though... or the tensor that has the smaller shape would have 0s filled in where there is no information.

Allegedly, tensors on the cpu and numpy arrays can share underlying memory locations; changing one will change the other.

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n= t.numpy() # Converts the tensor to a NumPy array
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Additionally, a change in the tensor will result in a change in the numpy array

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


We can also show that changes in the numpy array result in changes in the tensor

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


End of Tensor lesson